spring:
  application:
    name: Route-Guide-Backend
  profiles:
    active: local
    group:
      "local" : "local, secrets"
      "dev" : "dev, secrets"
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
