version : '3'

services:
  db:
    build:
      context : ../
      dockerfile : ./docker/db-container/Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    networks:
      - my-network

  server:
    build:
      context: ../
      dockerfile: ./docker/server-container/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    networks:
      - my-network


networks:
  my-network:
